openapi: 3.0.3
info:
  title: SQ1 Discovery APIs
  version: 0.0.0
paths:
  /all-assets/:
    get:
      operationId: all_assets_retrieve
      tags:
      - all-assets
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /check-status-freshservice/:
    get:
      operationId: check_status_freshservice_retrieve
      tags:
      - check-status-freshservice
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /check-status-jira/:
    get:
      operationId: check_status_jira_retrieve
      tags:
      - check-status-jira
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /create-ticket-manually-freshservice/:
    get:
      operationId: create_ticket_manually_freshservice_retrieve
      tags:
      - create-ticket-manually-freshservice
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: create_ticket_manually_freshservice_destroy
      tags:
      - create-ticket-manually-freshservice
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /create-ticket-manually-jira/:
    get:
      operationId: create_ticket_manually_jira_retrieve
      tags:
      - create-ticket-manually-jira
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /create-user/:
    post:
      operationId: create_user_create
      tags:
      - create-user
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /create_trello_card/:
    get:
      operationId: create_trello_card_retrieve
      tags:
      - create_trello_card
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: create_trello_card_destroy
      tags:
      - create_trello_card
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /delete-all-tickets-freshservice/:
    get:
      operationId: delete_all_tickets_freshservice_retrieve
      tags:
      - delete-all-tickets-freshservice
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /delete_jira_issues/:
    delete:
      operationId: delete_jira_issues_destroy
      tags:
      - delete_jira_issues
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /get-asset-details/{id}/:
    get:
      operationId: get_asset_details_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - get-asset-details
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /schemas/:
    get:
      operationId: schemas_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schemas
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /update-jira-exploits-patches/:
    get:
      operationId: update_jira_exploits_patches_retrieve
      tags:
      - update-jira-exploits-patches
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /update-ticket-manually-freshservice/:
    get:
      operationId: update_ticket_manually_freshservice_retrieve
      tags:
      - update-ticket-manually-freshservice
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /update-trello-exploits-patches/:
    get:
      operationId: update_trello_exploits_patches_retrieve
      tags:
      - update-trello-exploits-patches
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
components:
  schemas:
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
